export const environment = {
  production: true,
  jwt_username: 'jwtclient',
  jwt_password: 'Pass!234',
  recaptcha_site_key: '6LfGb7IZAAAAAEHRPV92z1mzLmZcnd4xbbW_rvhH',
  jitsiDomain: 'meet.bynfor.com',
  ftpBase: 'https://sftp.bynfor.com',

  AUTH_API_ENDPOINT: 'https://dev-gateway-api.bynfor.com/auth',
  API_ENDPOINT: 'https://dev-gateway-api.bynfor.com/inventory',
  MERCHANT_API_ENDPOINT: 'https://dev-gateway-api.bynfor.com/merchant',
  API_ENDPOINT_CUSTOMER: 'https://dev-gateway-api.bynfor.com/customer',
  API_ENDPOINT_PAYMENT: 'https://dev-gateway-api.bynfor.com/payment',
  API_ENDPOINT_NOTIFICATION: 'https://dev-gateway-api.bynfor.com/notification',
  API_ENDPOINT_AUCTION: 'https://dev-gateway-api.bynfor.com/auction',
  API_ENDPOINT_STORE: 'https://dev-gateway-api.bynfor.com/store',
  API_ENDPOINT_SHIPPING: 'https://dev-gateway-api.bynfor.com/shipping',
  API_ENDPOINT_MERCHANT: 'https://dev-gateway-api.bynfor.com/merchant',
  API_ENDPOINT_MEMBERSHIP: 'https://dev-gateway-api.bynfor.com/rewards',
  API_ENDPOINT_SOCKET_IO: 'https://realtime-db.bynfor.com',
  API_OPERRTEL: 'https://devapi.operrtel.com/api/v1',

  bynforPrefix: '697',
  facebookOauthClientId: '348855182911418',
  googleOauthClientId: '1076923135244-jackelkorh9n7n1nejri7hl3btnq1928.apps.googleusercontent.com',
  firebase: {
    apiKey: "AIzaSyA74aQoDZXS7QBTOEGZO6c0Icq7LKCpG5Q",
    authDomain: "bynfor-dev.firebaseapp.com",
    databaseURL: "https://bynfor-dev.firebaseio.com",
    projectId: "bynfor-dev",
    storageBucket: "bynfor-dev.appspot.com",
    messagingSenderId: "219427008319",
    appId: "1:219427008319:web:14073306d2af8af9cf2d8a",
    measurementId: "G-XSXZG15J65"
  },
  uspsUserId: '041FREEL4941',
  unsplashAccessKey: '3psQ9x5bYnIuPTB2rol1Hqj6Ex1a6gYXh3bo97zIRQQ',
  appId: '3FnXZN7JxE0JwUNaW5DM',
  secretKey: '4clAE2PrTvv32Rk0ywSXP4Kcuph0JEwcgOi9tBI4',
  environment: '', // DEV | QA | PROD | empty string // used in in home page generic username settings, it can be empty
  fe_url: 'https://dev.bynfor.com/',
  MAIN_SITE_URL: "https://dev.bynfor.com/",
  TOKEN_QUERY_KEYS: ['token', 'access_token'],
  LS_TOKEN_KEY: 'bynfor_access_token',
};
